name: JMH Benchmarks

on:
  workflow_dispatch:
    inputs:
      benchmark-class:
        description: 'Select benchmark class to run'
        required: true
        default: 'FixJsonCodecBenchmark'
        type: choice
        options:
          - FixJsonCodecBenchmark

jobs:
  throughput:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build parser with Maven
        run: mvn -B clean install --file submodules/fix-parser/pom.xml

      - run: mvn clean package -DskipTests

      - name: Run Throughput Benchmark
        run: |
          java -jar fix-benchmark/target/fix-benchmark-1.0-SNAPSHOT.jar \
            -bm Throughput -f 1 -wi 3 -i 5 -t 1 \
            -rff result_thrput.json

  latency:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build parser with Maven
        run: mvn -B clean install --file submodules/fix-parser/pom.xml

      - run: mvn clean package -DskipTests

      - name: Run Latency Benchmark
        run: |
          java -jar fix-benchmark/target/fix-benchmark-1.0-SNAPSHOT.jar \
            -bm AverageTime -f 1 -wi 3 -i 5 -t 1 \
            -rff result_lat.json